minetest.unregister_item("scifi_nodes:eyetree")
minetest.unregister_item("scifi_nodes:flower1")
minetest.unregister_item("scifi_nodes:flower2")
minetest.unregister_item("scifi_nodes:flower3")
minetest.unregister_item("scifi_nodes:flower4")
minetest.unregister_item("scifi_nodes:grass")
minetest.unregister_item("scifi_nodes:plant1")
minetest.unregister_item("scifi_nodes:plant10")
minetest.unregister_item("scifi_nodes:plant2")
minetest.unregister_item("scifi_nodes:plant3")
minetest.unregister_item("scifi_nodes:plant4")
minetest.unregister_item("scifi_nodes:plant5")
minetest.unregister_item("scifi_nodes:plant6")
minetest.unregister_item("scifi_nodes:plant7")
minetest.unregister_item("scifi_nodes:plant8")
minetest.unregister_item("scifi_nodes:plant9")
minetest.unregister_item("scifi_nodes:plant_trap")

print("[MOD] scifi_nodes_unregister loaded!")